export const books = [
  { id: 1, title: 'El Principito', price: 10.99, coverImage: '', description: 'Un clásico de la literatura mundial.' },
  { id: 2, title: 'Cien Años de Soledad', price: 15.99, coverImage: '', description: 'Obra maestra de Gabriel García Márquez.' },
  { id: 3, title: '1984', price: 12.50, coverImage: '', description: 'Distopía política escrita por George Orwell.' },
  { id: 4, title: 'Matar a un Ruiseñor', price: 18.00, coverImage: '', description: 'Historia de la justicia y la desigualdad racial.' },
  { id: 5, title: 'Don Quijote de la Mancha', price: 20.00, coverImage: '', description: 'La famosa obra de Cervantes que define la literatura española.' },
  { id: 6, title: 'El Gran Gatsby', price: 14.99, coverImage: '', description: 'Tragedia de la vida americana durante los años 20.' },
  { id: 7, title: 'Orgullo y Prejuicio', price: 13.00, coverImage: '', description: 'Una novela sobre el amor y los malentendidos sociales.' },
  { id: 8, title: 'Ulises', price: 21.50, coverImage: '', description: 'Una de las novelas más complejas y modernas de James Joyce.' },
  { id: 9, title: 'La Odisea', price: 9.99, coverImage: '', description: 'La obra maestra de Homero sobre la aventura y la perseverancia.' },
  { id: 10, title: 'Crimen y Castigo', price: 16.00, coverImage: '', description: 'La historia de un crimen y su terrible consecuencia moral.' },
  { id: 11, title: 'El Hobbit', price: 10.75, coverImage: '', description: 'Un cuento fantástico sobre el viaje de Bilbo Baggins.' },
  { id: 12, title: 'Harry Potter y la Piedra Filosofal', price: 19.99, coverImage: '', description: 'El inicio de la famosa saga de Harry Potter.' },
  { id: 13, title: 'El Código Da Vinci', price: 17.50, coverImage: '', description: 'Un thriller que combina arte, historia y misterio.' },
  { id: 14, title: 'Los Miserables', price: 22.00, coverImage: '', description: 'Una de las novelas más importantes de la literatura francesa.' },
  { id: 15, title: 'La Metamorfosis', price: 12.99, coverImage: '', description: 'Un cuento corto de Franz Kafka sobre la transformación.' },
  { id: 16, title: 'La Sombra del Viento', price: 19.00, coverImage: '', description: 'Un misterioso viaje por los libros perdidos en la Barcelona de la posguerra.' },
  { id: 17, title: 'Cien Poemas de Amor', price: 8.50, coverImage: '', description: 'Una colección de poesías de amor y desamor.' },
  { id: 18, title: 'Fahrenheit 451', price: 14.00, coverImage: '', description: 'Un clásico de la literatura distópica que habla sobre la censura.' },
  { id: 19, title: 'La Casa de los Espíritus', price: 18.99, coverImage: '', description: 'La historia de una familia chilena a lo largo de generaciones.' },
  { id: 20, title: 'El Alquimista', price: 13.50, coverImage: '', description: 'Una novela filosófica de Paulo Coelho sobre los sueños y la realización personal.' },
  { id: 21, title: 'El Lobo Estepario', price: 16.50, coverImage: '', description: 'Una exploración del individuo y la sociedad en una obra maestra de Hermann Hesse.' },
  { id: 22, title: 'La Guerra y la Paz', price: 24.00, coverImage: '', description: 'Una obra épica sobre la Rusia imperial y sus guerras.' },
  { id: 23, title: 'En Busca del Tiempo Perdido', price: 19.99, coverImage: '', description: 'La famosa obra de Marcel Proust sobre la memoria y el tiempo.' },
  { id: 24, title: 'El Nombre de la Rosa', price: 20.50, coverImage: '', description: 'Un misterio medieval ambientado en un monasterio.' },
  { id: 25, title: 'Moby Dick', price: 13.00, coverImage: '', description: 'La famosa novela de Herman Melville sobre el capitán Ahab y la ballena blanca.' },
  { id: 26, title: 'La Isla del Tesoro', price: 10.00, coverImage: '', description: 'Una clásica historia de aventuras y piratas.' },
  { id: 27, title: 'Anna Karenina', price: 18.00, coverImage: '', description: 'Una novela sobre el amor, la infidelidad y la tragedia.' },
  { id: 28, title: 'Drácula', price: 14.00, coverImage: '', description: 'La famosa novela de terror gótico de Bram Stoker.' },
  { id: 29, title: 'El Perfume', price: 15.00, coverImage: '', description: 'La historia de un hombre obsesionado por los olores.' },
  { id: 30, title: 'El Señor de los Anillos', price: 25.99, coverImage: '', description: 'Una trilogía épica de fantasía sobre la lucha contra el mal.' },
  { id: 31, title: 'El Club de la Lucha', price: 14.99, coverImage: '', description: 'Una novela de Chuck Palahniuk sobre la identidad y la sociedad moderna.' },
  { id: 32, title: 'La Naranja Mecánica', price: 12.99, coverImage: '', description: 'Un clásico de la literatura distópica sobre el control mental y la violencia.' },
  { id: 33, title: 'El Retrato de Dorian Gray', price: 18.00, coverImage: '', description: 'Una novela sobre la moralidad y la vanidad, escrita por Oscar Wilde.' },
  { id: 34, title: 'La Trilogía de la Fundación', price: 28.00, coverImage: '', description: 'Una serie de ciencia ficción de Isaac Asimov sobre la caída de un imperio galáctico.' },
  { id: 35, title: 'Las Aventuras de Sherlock Holmes', price: 11.50, coverImage: '', description: 'Las aventuras del famoso detective creado por Arthur Conan Doyle.' },
  { id: 36, title: 'Fahrenheit 451', price: 12.50, coverImage: '', description: 'Una crítica social sobre la censura y el control del conocimiento.' },
  { id: 37, title: 'La Casa de Papel', price: 16.00, coverImage: '', description: 'Un thriller sobre un robo monumental planeado por un grupo de criminales.' },
  { id: 38, title: 'La Sombra de los Vientos', price: 19.50, coverImage: '', description: 'Una novela de misterio y amor en la Barcelona de posguerra.' },
  { id: 39, title: 'El Corazón de las Tinieblas', price: 13.50, coverImage: '', description: 'Una historia de exploración y colonización en el Congo.' },
  { id: 40, title: 'Los Pilares de la Tierra', price: 22.50, coverImage: '', description: 'Una novela histórica épica sobre la construcción de una catedral en la Edad Media.' },
  { id: 41, title: 'El Código de Da Vinci', price: 17.00, coverImage: '', description: 'Un thriller que une arte, religión y misterio en una emocionante trama.' },
  { id: 42, title: 'El Viento en los Sauces', price: 14.50, coverImage: '', description: 'Un clásico de la literatura infantil inglesa.' },
  { id: 43, title: 'Crónica de una Muerte Anunciada', price: 11.00, coverImage: '', description: 'Una novela de Gabriel García Márquez sobre el destino y el honor.' },
  { id: 44, title: 'Viaje al Centro de la Tierra', price: 12.00, coverImage: '', description: 'Una novela de aventuras y ciencia ficción de Julio Verne.' },
  { id: 45, title: 'El Silmarillion', price: 18.50, coverImage: '', description: 'El mundo mitológico de J.R.R. Tolkien, precursor de El Señor de los Anillos.' },
  { id: 46, title: 'Los Hombres que no Amaban a las Mujeres', price: 14.00, coverImage: '', description: 'Un thriller de misterio y crimen de Stieg Larsson.' },
  { id: 47, title: 'El Nombre del Viento', price: 19.00, coverImage: '', description: 'La historia de un hombre que se convierte en leyenda, narrada por él mismo.' },
  { id: 48, title: 'La Chica del Tren', price: 13.00, coverImage: '', description: 'Un thriller psicológico lleno de giros inesperados.' },
  { id: 49, title: 'El Ladrón de la Mente', price: 17.00, coverImage: '', description: 'Una novela de ciencia ficción que explora la mente humana y el robo de recuerdos.' },
  { id: 50, title: 'En el Camino', price: 11.50, coverImage: '', description: 'Una obra clave del movimiento beat en Estados Unidos.' },
  { id: 51, title: 'La Noche de los Tiempos', price: 20.00, coverImage: '', description: 'Una novela de ciencia ficción sobre la humanidad y su evolución.' },
  { id: 52, title: 'La Caverna', price: 18.00, coverImage: '', description: 'Una novela sobre la alienación y la búsqueda de la libertad.' },
  { id: 53, title: 'El Retrato de Dorian Gray', price: 16.50, coverImage: '', description: 'Una obra de Oscar Wilde sobre la vanidad, el ego y la moral.' },
  { id: 54, title: 'La Quinta Estación', price: 19.99, coverImage: '', description: 'Una novela de ciencia ficción sobre el fin del mundo y la lucha por la supervivencia.' },
  { id: 55, title: 'Los Detectives Salvajes', price: 18.00, coverImage: '', description: 'Una obra literaria que combina poesía, narrativa y exploración de la literatura latinoamericana.' },
  { id: 56, title: 'Bajo la Misma Estrella', price: 15.00, coverImage: '', description: 'Una emotiva historia sobre el amor y la enfermedad.' },
  { id: 57, title: 'La Princesa Prometida', price: 13.00, coverImage: '', description: 'Una historia de aventuras, amor y humor.' },
  { id: 58, title: 'Soy Leyenda', price: 14.00, coverImage: '', description: 'Una novela de terror y ciencia ficción sobre un hombre sobreviviente de una plaga.' },
  { id: 59, title: 'La Peste', price: 17.00, coverImage: '', description: 'Una obra maestra de Albert Camus sobre la vida y la muerte en tiempos de crisis.' },
  { id: 60, title: '1984', price: 16.50, coverImage: '', description: 'Un clásico de la literatura distópica de George Orwell.' },
  { id: 61, title: 'El Hombre en el Castillo', price: 19.00, coverImage: '', description: 'Una historia alternativa de un mundo donde los nazis ganaron la Segunda Guerra Mundial.' },
  { id: 62, title: 'Los Instrucciones', price: 21.00, coverImage: '', description: 'Un relato fantástico que desafía la narrativa tradicional.' },
  { id: 63, title: 'El Exorcista', price: 20.50, coverImage: '', description: 'Una novela de terror sobre la posesión demoníaca.' },
  { id: 64, title: 'La Larga Marcha', price: 18.50, coverImage: '', description: 'Un relato distópico sobre una competencia mortal de resistencia.' },
  { id: 65, title: 'La Noche Más Oscura', price: 12.00, coverImage: '', description: 'Un thriller que explora los miedos más profundos de la humanidad.' },
  { id: 66, title: 'Cuentos de la Abuela Amelia', price: 9.00, coverImage: '', description: 'Historias infantiles llenas de sabiduría popular.' },
  { id: 67, title: 'El Último Hombre', price: 13.50, coverImage: '', description: 'Una historia post-apocalíptica sobre los últimos días de la humanidad.' },
  { id: 68, title: 'El Juego de Ender', price: 15.50, coverImage: '', description: 'Una novela de ciencia ficción sobre un niño prodigio en un campo de batalla galáctico.' },
  { id: 69, title: 'Matar a un Ruiseñor', price: 14.50, coverImage: '', description: 'Una historia sobre la injusticia racial en el sur de los Estados Unidos.' },
  { id: 70, title: 'Elogio de la Sombra', price: 11.00, coverImage: '', description: 'Un ensayo filosófico de Junichiro Tanizaki sobre la cultura japonesa.' },
  { id: 71, title: 'La Guerra de los Mundos', price: 16.00, coverImage: '', description: 'Un clásico de la ciencia ficción de H.G. Wells sobre una invasión extraterrestre.' },
  { id: 72, title: 'La Broma Infinita', price: 23.00, coverImage: '', description: 'Una novela compleja sobre la vida moderna y el entretenimiento.' },
  { id: 73, title: 'En el Corazón de la Oscuridad', price: 14.00, coverImage: '', description: 'Una historia de exploración y colonialismo en el Congo.' },
  { id: 74, title: 'El Último Juego', price: 14.00, coverImage: '', description: 'Una novela de ciencia ficción sobre un juego de azar en el espacio.' },
  { id: 75, title: 'El Jardín de los Cerezos', price: 12.50, coverImage: '', description: 'Una obra de teatro de Anton Chekhov sobre la vida y la muerte.' },
  { id: 76, title: 'La Divina Comedia', price: 18.00, coverImage: '', description: 'El clásico de Dante Alighieri sobre el viaje a través del Infierno, Purgatorio y Paraíso.' },
  { id: 77, title: 'Frankenstein', price: 12.50, coverImage: '', description: 'La famosa novela de Mary Shelley sobre el creador y su monstruo.' },
  { id: 78, title: 'El Hobbit', price: 13.50, coverImage: '', description: 'La historia que precede al Señor de los Anillos, sobre las aventuras de Bilbo Baggins.' },
  { id: 79, title: 'El Último de los Mohicanos', price: 15.00, coverImage: '', description: 'Una historia de guerra y supervivencia en América del Norte durante la colonización.' },
  { id: 80, title: 'El Conde de Montecristo', price: 20.00, coverImage: '', description: 'Una novela sobre venganza, traición y redención de Alexandre Dumas.' },
  { id: 81, title: 'La Odisea', price: 17.50, coverImage: '', description: 'El épico poema de Homero sobre las aventuras de Odiseo en su regreso a casa.' },
  { id: 82, title: '1984', price: 18.00, coverImage: '', description: 'La famosa distopía de George Orwell sobre un régimen totalitario que controla todos los aspectos de la vida.' },
  { id: 83, title: 'Los Miserables', price: 25.00, coverImage: '', description: 'Una novela de Victor Hugo sobre la justicia, la pobreza y la redención en la Francia del siglo XIX.' },
  { id: 84, title: 'El Retrato de Dorian Gray', price: 15.00, coverImage: '', description: 'Una novela de Oscar Wilde sobre el culto a la belleza y la moralidad.' },
  { id: 85, title: 'El Maestro y Margarita', price: 19.00, coverImage: '', description: 'Una obra literaria de Mijaíl Bulgákov que mezcla lo fantástico y lo real en la Rusia soviética.' },
  { id: 86, title: 'Matar a un Ruiseñor', price: 13.50, coverImage: '', description: 'Una historia sobre la lucha por la justicia y la igualdad racial en el sur de los Estados Unidos.' },
  { id: 87, title: 'El Hombre Invisible', price: 14.00, coverImage: '', description: 'Una novela de H.G. Wells sobre un hombre que se vuelve invisible y pierde su humanidad.' },
  { id: 88, title: 'Drácula', price: 16.00, coverImage: '', description: 'El famoso relato de terror de Bram Stoker sobre el vampiro condesa Drácula.' },
  { id: 89, title: 'Don Quijote de la Mancha', price: 22.00, coverImage: '', description: 'La clásica obra de Cervantes sobre las aventuras del caballero loco y su fiel escudero.' },
  { id: 90, title: 'El Amor en los Tiempos del Cólera', price: 17.00, coverImage: '', description: 'Una novela de Gabriel García Márquez sobre el amor, la pasión y el paso del tiempo.' },
  { id: 91, title: 'El Héroe de las Mil Caras', price: 18.00, coverImage: '', description: 'Un análisis de la mitología comparada de Joseph Campbell sobre el viaje del héroe.' },
  { id: 92, title: 'La Guerra de los Mundos', price: 16.00, coverImage: '', description: 'Una novela clásica de ciencia ficción de H.G. Wells sobre una invasión marciana.' },
  { id: 93, title: 'La Casa de los Espíritus', price: 17.00, coverImage: '', description: 'Una novela de Isabel Allende sobre una familia chilena y su conexión con lo sobrenatural.' },
  { id: 94, title: 'Las Aventuras de Sherlock Holmes', price: 15.00, coverImage: '', description: 'Una colección de relatos sobre el detective más famoso de la literatura, Sherlock Holmes.' },
  { id: 95, title: 'En Busca del Tiempo Perdido', price: 21.00, coverImage: '', description: 'Una obra monumental de Marcel Proust sobre la memoria, el tiempo y la nostalgia.' },
  { id: 96, title: 'El Juego de Ender', price: 16.50, coverImage: '', description: 'Una novela de ciencia ficción sobre un niño prodigio entrenado para defender la humanidad.' },
  { id: 97, title: 'El Hobbit', price: 12.00, coverImage: '', description: 'La historia de las aventuras de Bilbo Baggins en la Tierra Media.' },
  { id: 98, title: 'Harry Potter y la Piedra Filosofal', price: 19.50, coverImage: '', description: 'El primer libro de la famosa serie sobre el joven mago Harry Potter.' },
  { id: 99, title: 'Los Tres Mosqueteros', price: 17.00, coverImage: '', description: 'Una novela histórica de Alexandre Dumas sobre honor y lealtad.' },
  { id: 100, title: 'La Isla del Tesoro', price: 14.00, coverImage: '', description: 'Una clásica historia de aventuras de piratas y búsqueda de tesoros.' }
];